spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:postgresql://localhost:5432/doctor_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
eureka:
  client:
    service-url:
      default: http://localhost:8761:eureka/
    fetch-registry: true
    register-with-eureka: true